### ISSUE TITLE
Scss conversion problems

### ISSUE THREAD

**Issue by g7sim** [ajlkn/responsive-tools#12]
No online scss to css - converter is able to convert Your scss. Can You please add the css'es !

**Comment by andrewalba** [comment]
You can install https://sass-lang.com/dart-sass and convert. The process is fairly straightforward.

**Comment by g7sim** [comment]
You must be joking ! All i have is scssphp 1.20. Bootstrap5 has been done with dart sass ( - also[ Django](https://stackoverflow.com/questions/68049871/bootstrap-5-sass-by-dart-sass)):  I need for that Node.js etc. 
The other possibility is [scout](https://github.com/scout-app/scout-app) - also for Windows, which also uses node.
Or at windows - powershell - command line : choco install sass  and then choco install chocolateygui  (or [from git](https://github.com/chocolatey)).

To [connect dart to html](https://dart.dev/tutorials/web/low-level-html/connect-dart-html) is not for normal users who just want to make a template.
If i paste the code at [dartdev](https://dartpad.dev/), it gives only errors
Dont You want that people use Yor tools ?

**Comment by andrewalba** [comment]
Just some clarifications. I am a developer who has used this repository in the past and not the developer. There is no problem with converting SCSS in this repository into CSS.

The link I provided is for a common solution that developers use to convert SCSS to CSS. It is easy to install via NPM or Yarn and really easy to compile CSS from SCSS.

If you are unsure how to generate the CSS I don't understand why you would want to use this repository as a framework to build a responsive site or web app. If you want everything **compiled** for you, think about just grabbing the CSS from some of the developer's free examples at https://html5up.net/ or look at paying for a month at https://pixelarity.com/.

Good luck.

**Comment by g7sim** [comment]
I You look at html5up.net, they use only extractions of Your scss (example : arcana ). But there are many other template- frameworks (codepen).
